name: Publish Package to npmjs
# run when v<MAJOR>.<MINOR>.<PATCH> tag is pushed...
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    # ...but only when the workflow is triggered by a branch or lightweight tag placed on the last commit of the `main` branch
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm install
          npm run-script nuke:test
      - run: |
          cd target
          npm publish --dry-run esbuild-peggy-latest.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
