name: Publish Package to npmjs
# run when v<MAJOR>.<MINOR>.<PATCH> tag is pushed...
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: build-and-test
        run: |
          npm install
          npm run-script nuke:test
      - name: publish-to-npm
        run: |
          cd target
          npm publish esbuild-peggy-latest.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
